// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMRCpP1EjbZzLhLId-zf7trKlmRygPgXI',
    appId: '1:848782040223:web:0f5a7a22920d3ecff416aa',
    messagingSenderId: '848782040223',
    projectId: 'smart-plant-f3171',
    authDomain: 'smart-plant-f3171.firebaseapp.com',
    databaseURL: 'https://smart-plant-f3171-default-rtdb.firebaseio.com',
    storageBucket: 'smart-plant-f3171.firebasestorage.app',
    measurementId: 'G-HDYMWRGRTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB62IZUCeHXOFa0UPd6jPxmW7c2PrINGE',
    appId: '1:848782040223:android:fae2fc2806c4fb31f416aa',
    messagingSenderId: '848782040223',
    projectId: 'smart-plant-f3171',
    databaseURL: 'https://smart-plant-f3171-default-rtdb.firebaseio.com',
    storageBucket: 'smart-plant-f3171.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0RbyZruR0dBUp9akHtCwhwpJyBqpRhGg',
    appId: '1:848782040223:ios:fd02db614993368df416aa',
    messagingSenderId: '848782040223',
    projectId: 'smart-plant-f3171',
    databaseURL: 'https://smart-plant-f3171-default-rtdb.firebaseio.com',
    storageBucket: 'smart-plant-f3171.firebasestorage.app',
    iosBundleId: 'com.example.smartPlantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0RbyZruR0dBUp9akHtCwhwpJyBqpRhGg',
    appId: '1:848782040223:ios:fd02db614993368df416aa',
    messagingSenderId: '848782040223',
    projectId: 'smart-plant-f3171',
    databaseURL: 'https://smart-plant-f3171-default-rtdb.firebaseio.com',
    storageBucket: 'smart-plant-f3171.firebasestorage.app',
    iosBundleId: 'com.example.smartPlantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMRCpP1EjbZzLhLId-zf7trKlmRygPgXI',
    appId: '1:848782040223:web:9759797d69c52fc7f416aa',
    messagingSenderId: '848782040223',
    projectId: 'smart-plant-f3171',
    authDomain: 'smart-plant-f3171.firebaseapp.com',
    databaseURL: 'https://smart-plant-f3171-default-rtdb.firebaseio.com',
    storageBucket: 'smart-plant-f3171.firebasestorage.app',
    measurementId: 'G-GVTQQMJ8JM',
  );
}
